name: Cypress Test

on:
  push:
    branches:
      - '**/feature-**'
      - '**/feature-**'
      - 'develop'
    paths-ignore:
      - 'main.yml'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run start
