name: Cypress Test
  
on:
  push:
    branches:
      - '*'
    
jobs:
  cypress-run:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn start
      
